package com.ctco.day5;// Generated by Selenium IDE

import org.junit.jupiter.api.*;
import org.openqa.selenium.JavascriptExecutor;
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.firefox.FirefoxDriver;

import java.util.HashMap;
import java.util.Map;

import static net.bytebuddy.matcher.ElementMatchers.is;

public class FirstTestTest {
    private WebDriver driver;
    private Map<String, Object> vars;
    JavascriptExecutor js;
    @BeforeEach
    public  void setUp() {
        System.setProperty("webdriver.gecko.driver", "C:\\SRDEV\\geckodriver.exe");
        driver = new FirefoxDriver();
    }
    @AfterEach
    public void tearDown() {
        driver.quit();
    }
    @Test
    public void firstTest() {
        driver.get("https://ctco.lv/");
        Assertions.assertEquals(driver.getTitle(), "C.T.Co People");
    }
}
