package com.ctco.day5;// Generated by Selenium IDE

import org.junit.jupiter.api.*;
import org.openqa.selenium.By;
import org.openqa.selenium.Dimension;
import org.openqa.selenium.JavascriptExecutor;
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.firefox.FirefoxDriver;

import java.util.HashMap;
import java.util.Map;

import static net.bytebuddy.matcher.ElementMatchers.is;

public class FirstTestTest {
    private WebDriver driver;
    private Map<String, Object> vars;
    JavascriptExecutor js;
    @BeforeEach
    public  void setUp() {
        System.setProperty("webdriver.gecko.driver", "C:\\SRDEV\\geckodriver.exe");
        driver = new FirefoxDriver();
    }
    @AfterEach
    public void tearDown() {
        driver.quit();
    }
    @Test
    public void firstTest() {
        driver.get("https://ctco.lv/");
        Assertions.assertEquals(driver.getTitle(), "C.T.Co People");
    }

    @Test
    public void ctcoDarbnieks() {
        driver.manage().window().setSize(new Dimension(946, 691));
        js.executeScript("window.scrollTo(0,0)");
        driver.findElement(By.cssSelector(".col-sm-9 > .text-block .button-bg")).click();
        driver.findElement(By.id("menu-item-3782")).click();
        driver.findElement(By.linkText("Test Automation Engineer")).click();
        driver.close();
        String bodyText = driver.findElement(By.cssSelector(".animated > .text-block p:nth-child(3)")).getText();
        Assertions.assertTrue( bodyText.contains("Experience with automated testing tools and frameworks (for example: Selenium, REST Assured);"));
     //   Assertions.assertEquals(driver.getTitle(), "C.T.Co People");
    }
}
